'use strict';import{AssertionError,AttributeError,BaseException,DeprecationWarning,Exception,IndexError,IterableError,KeyError,NotImplementedError,RuntimeWarning,StopIteration,UserWarning,ValueError,Warning,__JsIterator__,__PyIterator__,__Terminal__,__add__,__and__,__call__,__class__,__envir__,__eq__,__floordiv__,__ge__,__get__,__getcm__,__getitem__,__getslice__,__getsm__,__gt__,__i__,__iadd__,__iand__,__idiv__,__ijsmod__,__ilshift__,__imatmul__,__imod__,__imul__,__in__,__init__,__ior__,__ipow__,
__irshift__,__isub__,__ixor__,__jsUsePyNext__,__jsmod__,__k__,__kwargtrans__,__le__,__lshift__,__lt__,__matmul__,__mergefields__,__mergekwargtrans__,__mod__,__mul__,__ne__,__neg__,__nest__,__or__,__pow__,__pragma__,__pyUseJsNext__,__rshift__,__setitem__,__setproperty__,__setslice__,__sort__,__specialattrib__,__sub__,__super__,__t__,__terminal__,__truediv__,__withblock__,__xor__,abs,all,any,assert,bool,bytearray,bytes,callable,chr,copy,deepcopy,delattr,dict,dir,divmod,enumerate,filter,float,getattr,
hasattr,input,int,isinstance,issubclass,len,list,map,max,min,object,ord,pow,print,property,py_TypeError,py_iter,py_metatype,py_next,py_reversed,py_typeof,range,repr,round,set,setattr,sorted,str,sum,tuple,zip}from"./org.transcrypt.__runtime__.js";import*as random_py from"./random.js";var __name__="wizardlib";export var _valid_colors=["white","silver","gray","black","red","maroon","yellow","olive","lime","green","aqua","teal","blue","navy","fuchsia","purple","orange","mediumvioletred","deeppink","palevioletred",
"hotpink","lightpink","pink","darkred","firebrick","crimson","indianred","lightcoral","salmon","darksalmon","lightsalmon","orangered","tomato","darkorange","coral","darkkhaki","gold","khaki","peachpuff","palegoldenrod","moccasin","papayawhip","lightgoldenrodyellow","lemonchiffon","lightyellow","brown","saddlebrown","sienna","chocolate","darkgoldenrod","peru","rosybrown","goldenrod","sandybrown","tan","burlywood","wheat","navajowhite","bisque","blanchedalmond","cornsilk","darkgreen","darkolivegreen",
"forestgreen","seagreen","olivedrab","mediumseagreen","limegreen","springgreen","mediumspringgreen","darkseagreen","mediumaquamarine","yellowgreen","lawngreen","chartreuse","lightgreen","greenyellow","palegreen","darkcyan","lightseagreen","cadetblue","darkturquoise","mediumturquoise","turquoise","cyan","aquamarine","paleturquoise","lightcyan","darkblue","mediumblue","midnightblue","royalblue","steelblue","dodgerblue","deepskyblue","cornflowerblue","skyblue","lightskyblue","lightsteelblue","lightblue",
"powderblue","indigo","darkmagenta","darkviolet","darkslateblue","blueviolet","darkorchid","magenta","slateblue","mediumslateblue","mediumorchid","mediumpurple","orchid","violet","plum","thistle","lavender","mistyrose","antiquewhite","linen","beige","whitesmoke","lavenderblush","oldlace","aliceblue","seashell","ghostwhite","honeydew","floralwhite","azure","mintcream","snow","ivory","darkslategray","dimgray","slategray","lightslategray","darkgray","lightgray","gainsboro"];export var _is_valid_element=
function(func_name){var decorator=function(func){var wrapper=function(){var args=tuple([].slice.apply(arguments).slice(0));var element=args[0];if(isinstance(element,tuple([float,int,str]))){var __except0__=Exception("Error in {}(), invalid element passed as first  argument\n  - '{}' is not a valid element!\n  - Did you pass an element created with add_image(), add_text(), or add_button() as the first argument?\n".format(func_name,element));__except0__.__cause__=null;throw __except0__;}else if(callable(element)||
!element){var __except0__=Exception("Error in {}(), invalid element passed as first argument\n  - Did you pass an element created with add_image(), add_text(), or add_button() as the first argument?\n".format(func_name));__except0__.__cause__=null;throw __except0__;}return func(...args,__kwargtrans__(kwargs))};return wrapper};return decorator};export var add_audio=function(filename){var element=document.createElement("audio");element.addEventListener("error",_filename_not_found.bind(null,filename,
"add_audio"));element.src=filename;document.body.appendChild(element);return element};export var add_background=function(filename){var element=document.createElement("img");element.addEventListener("error",_filename_not_found.bind(null,filename,"add_background"));element.src=filename;var canvas=document.getElementById("canvas");if(canvas)canvas.style.backgroundImage="url({})".format(filename);else document.querySelector("html").style.backgroundImage="url({})".format(filename)};export var add_background_audio=
function(filename){var element=document.createElement("audio");element.addEventListener("error",_filename_not_found.bind(null,filename,"add_background_audio"));element.src=filename;element.id="bg-music";element.loop=true;document.body.appendChild(element)};export var add_button=function(text){var element=document.createElement("button");element.textContent=text;element.style.alignSelf="flex-start";var canvas=document.getElementById("canvas");if(canvas)canvas.appendChild(element);else document.body.appendChild(element);
return element};export var add_image=function(filename,size){if(typeof size=="undefined"||size!=null&&size.hasOwnProperty("__kwargtrans__"))var size=null;var element=document.createElement("img");element.addEventListener("error",_filename_not_found.bind(null,filename,"add_image"));element.src=filename;if(size)element.style.width=size+"px";var canvas=document.getElementById("canvas");if(canvas)canvas.appendChild(element);else document.body.appendChild(element);return element};export var add_text=function(text,
size){if(typeof size=="undefined"||size!=null&&size.hasOwnProperty("__kwargtrans__"))var size=18;var element=document.createElement("p");element.textContent=text;element.style.fontSize=size+"px";var canvas=document.getElementById("canvas");if(canvas)canvas.appendChild(element);else document.body.appendChild(element);return element};export var add_text_input=function(placeholder){var element=document.createElement("input");element.placeholder=placeholder;var canvas=document.getElementById("canvas");
if(canvas)canvas.appendChild(element);else document.body.appendChild(element);return element};export var animate_down=_is_valid_element("animate_down")(function(element,distance,time,loop){if(typeof time=="undefined"||time!=null&&time.hasOwnProperty("__kwargtrans__"))var time=8;if(typeof loop=="undefined"||loop!=null&&loop.hasOwnProperty("__kwargtrans__"))var loop=false;element.style.transition="{}s linear transform".format(time);var start_button=document.getElementById("start");if(start_button)start_button.addEventListener("click",
_translate_y.bind(null,element,distance));else _translate_y(element,distance);if(loop){element.animation_direction="up";element.addEventListener("transitionend",_loop_animation.bind(null,element,distance))}});export var animate_left=_is_valid_element("animate_left")(function(element,distance,time,loop){if(typeof time=="undefined"||time!=null&&time.hasOwnProperty("__kwargtrans__"))var time=8;if(typeof loop=="undefined"||loop!=null&&loop.hasOwnProperty("__kwargtrans__"))var loop=false;element.style.transition=
"{}s linear transform".format(time);var start_button=document.getElementById("start");if(start_button)start_button.addEventListener("click",_translate_x.bind(null,element,-distance));else _translate_x(element,-distance);if(loop){element.animation_direction="left";element.addEventListener("transitionend",_loop_animation.bind(null,element,distance))}});export var animate_right=_is_valid_element("animate_right")(function(element,distance,time,loop){if(typeof time=="undefined"||time!=null&&time.hasOwnProperty("__kwargtrans__"))var time=
8;if(typeof loop=="undefined"||loop!=null&&loop.hasOwnProperty("__kwargtrans__"))var loop=false;element.style.transition="{}s linear transform".format(time);var start_button=document.getElementById("start");if(start_button)start_button.addEventListener("click",_translate_x.bind(null,element,distance));else _translate_x(element,distance);if(loop){element.animation_direction="right";element.addEventListener("transitionend",_loop_animation.bind(null,element,distance))}});export var animate_up=_is_valid_element("animate_up")(function(element,
distance,time,loop){if(typeof time=="undefined"||time!=null&&time.hasOwnProperty("__kwargtrans__"))var time=8;if(typeof loop=="undefined"||loop!=null&&loop.hasOwnProperty("__kwargtrans__"))var loop=false;element.style.transition="{}s linear transform".format(time);var start_button=document.getElementById("start");if(start_button)start_button.addEventListener("click",_translate_y.bind(null,element,-distance));else _translate_y(element,-distance);if(loop){element.animation_direction="up";element.addEventListener("transitionend",
_loop_animation.bind(null,element,-distance))}});export var check_collision=function(element1,element2,function_to_run){if(isinstance(element1,tuple([float,int,str]))||isinstance(element2,tuple([float,int,str]))){var __except0__=Exception("Error in check_collision(), invalid element passed as first or second argument\n  - Did you pass an element created with add_image(), add_text(), or add_button() as the first or second argument?\n");__except0__.__cause__=null;throw __except0__;}if(callable(element1)||
callable(element2)||!(element1&&element2)){var __except0__=Exception("Error in check_collision(), invalid element passed as first or second argument\n  - Did you pass an element created with add_image(), add_text(), or add_button() as the first or second argument?\n");__except0__.__cause__=null;throw __except0__;}var start_button=document.getElementById("start");start_button.addEventListener("click",setInterval.bind(null,function __lambda__(){return _collision(element1,element2,function_to_run)},
50))};export var py_clear=function(){var image_elements=Array.prototype.slice.call(document.querySelectorAll("img"));var text_elements=Array.prototype.slice.call(document.querySelectorAll("p"));var button_elements=Array.prototype.slice.call(document.querySelectorAll("button:not(#start)"));var input_elements=Array.prototype.slice.call(document.querySelectorAll("input"));image_elements.map(function __lambda__(el){return el.remove()});text_elements.map(function __lambda__(el){return el.remove()});button_elements.map(function __lambda__(el){return el.remove()});
input_elements.map(function __lambda__(el){return el.remove()})};export var click=_is_valid_element("click")(function(element,function_to_run){if(!callable(function_to_run)){var __except0__=Exception("Error in click()\n\t - The second argument is not a function!");__except0__.__cause__=null;throw __except0__;}var click_handler=function(event){if(function_to_run.prototype.constructor.length)function_to_run(event.target);else function_to_run()};element.click_handler=click_handler;element.addEventListener("click",
click_handler)});export var _collision=function(a,b,cb){var a=a.getBoundingClientRect();var b=b.getBoundingClientRect();if(b.x<a.x+a.width&&b.x+b.width>a.x&&b.top<a.top+a.height&&b.top+b.height>a.top)cb()};export var fade_in=_is_valid_element("fade_in")(function(element){if(element.style.transition&&!__in__("opacity 1s linear",element.style.transition))element.style.transition+=", opacity 1s linear";else element.style.transition="opacity 1s linear";element.classList.remove("fade-out");element.classList.add("fade-in")});
export var fade_out=_is_valid_element("fade_out")(function(element){if(element.style.transition&&!__in__("opacity 1s linear",element.style.transition))element.style.transition+=", opacity 1s linear";else element.style.transition="opacity 1s linear";element.classList.remove("fade-in");element.classList.add("fade-out")});export var _filename_not_found=function(filename,function_name){var __except0__=Exception("Error in {}()\n  - '{}' is not a valid filename!".format(function_name,filename));__except0__.__cause__=
null;throw __except0__;};export var get_input_value=_is_valid_element("get_input_value")(function(element){return element.value});export var _loop_animation=_is_valid_element("_loop_animation")(function(element,distance){if(element.animation_direction=="left"){element.animation_direction="right";_translate_x(element,distance)}else if(element.animation_direction=="right"){element.animation_direction="left";_translate_x(element,-distance)}else if(element.animation_direction=="up"){element.animation_direction=
"down";_translate_y(element,-distance)}else if(element.animation_direction=="down"){element.animation_direction="up";_translate_y(element,distance)}});export var _is_invalid_color=function(color){if(!__in__(color.lower(),_valid_colors)){if(!color)return true;if(color[0]!="#")return true;if(len(color)!=7)return true}return false};export var _is_invalid_x_position_keyword=function(x_position){return!__in__(x_position,["left","right","center"])};export var _is_invalid_y_position_keyword=function(y_position){return!__in__(y_position,
["top","bottom","center"])};export var keydown=function(function_to_run){if(!callable(function_to_run)){var __except0__=Exception("Error in keydown()\n\t - The first argument is not a function!");__except0__.__cause__=null;throw __except0__;}var keydown_listener=function(event){function_to_run(event.key.toLowerCase())};document.body.addEventListener("keydown",keydown_listener)};export var move_down=_is_valid_element("move_down")(function(element,distance){element.style.position="absolute";element.style.top=
int(element.offsetTop)+distance+"px"});export var move_left=_is_valid_element("move_left")(function(element,distance){element.style.position="absolute";element.style.left=int(element.offsetLeft)+-distance+"px"});export var move_right=_is_valid_element("move_right")(function(element,distance){element.style.position="absolute";element.style.left=int(element.offsetLeft)+distance+"px"});export var move_up=_is_valid_element("move_up")(function(element,distance){element.style.position="absolute";element.style.top=
int(element.offsetTop)+-distance+"px"});export var play_audio=_is_valid_element("play_audio")(function(element){if(!element.paused){element.pause();element.currentTime=0}element.play()});export var position_element=_is_valid_element("position_element")(function(element,x,y){element.style.position="absolute";var get_flex_align=dict({"center":"center","right":"flex-end","left":"flex-start"});if(isinstance(x,str)){if(_is_invalid_x_position_keyword(x)){var __except0__=Exception("Error in position_element()\n  - '{}' is not a valid position shortcut!".format(x));
__except0__.__cause__=null;throw __except0__;}element.style.alignSelf=get_flex_align[x]}else element.style.left=x+"px";if(isinstance(y,str))if(_is_invalid_y_position_keyword(y)){var __except0__=Exception("Error in position_element()\n  - '{}' is not a valid position shortcut!".format(y));__except0__.__cause__=null;throw __except0__;}else if(y=="bottom")if(element.tagName=="IMG")element.onload=function __lambda__(_){return _set_y_to_bottom(element)};else _set_y_to_bottom(element);else if(y=="top")if(element.tagName==
"IMG")element.onload=function __lambda__(_){return _set_y_to_top(element)};else _set_y_to_top(element);else{if(y=="center")if(element.tagName=="IMG")element.onload=function __lambda__(_){return _set_y_to_center(element)};else _set_y_to_center(element)}else element.style.top=y+"px"});export var set_background_color=function(color){var element=document.querySelector("html");if(_is_invalid_color(color)){var __except0__=Exception("Error in set_background_color()\n  - '{}' is not a valid color name!".format(color));
__except0__.__cause__=null;throw __except0__;}element.style.backgroundColor=color.lower()};export var set_element_width=_is_valid_element("set_element_width")(function(element,width){element.style.width=width+"px"});export var set_font_size=_is_valid_element("set_font_size")(function(element,font_size){element.style.fontSize=str(font_size)+"px"});export var set_interval=function(function_to_run,time){var start_button=document.getElementById("start");if(start_button)start_button.addEventListener("click",
setInterval.bind(null,function_to_run,time*1E3));else setInterval(function_to_run,time*1E3)};export var set_text_color=_is_valid_element("set_text_color")(function(text_element,color){if(_is_invalid_color(color)){var __except0__=Exception("Error in set_text_color()\n  - '{}' is not a valid color name!".format(color));__except0__.__cause__=null;throw __except0__;}text_element.style.color=color});export var set_text_decoration=_is_valid_element("set_text_decoration")(function(text_element,decoration_string){text_element.style.textDecoration=
decoration_string});export var set_timeout=function(function_to_run,time){var start_button=document.getElementById("start");if(start_button)start_button.addEventListener("click",setTimeout.bind(null,function_to_run,time*1E3));else setTimeout(function_to_run,time*1E3)};export var _set_y_to_bottom=_is_valid_element("_set_y_to_bottom")(function(element){var canvas=document.querySelector("#canvas");if(canvas)element.style.top=canvas.offsetHeight-element.offsetHeight+"px";else element.style.top=window.innerHeight-
element.offsetHeight+"px"});export var _set_y_to_top=_is_valid_element("_set_y_to_top")(function(element){element.style.top=0+"px"});export var _set_y_to_center=_is_valid_element("_set_y_to_center")(function(element){var canvas=document.querySelector("#canvas");if(canvas)element.style.top=canvas.offsetHeight/2-element.offsetHeight/2+"px";else element.style.top=window.innerHeight/2-element.offsetHeight/2+"px"});export var _translate_x=_is_valid_element("_translate_x")(function(element,distance){element.style.transform=
"translateX({}px)".format(distance)});export var _translate_y=_is_valid_element("_translate_y")(function(element,distance){element.style.transform="translateY({}px)".format(distance)});export var update_text=_is_valid_element("update_text")(function(text_element,new_text){if(!isinstance(new_text,str)){var __except0__=Exception("Error in update_text(), the second argument is not a valid Python string!".format());__except0__.__cause__=null;throw __except0__;}text_element.textContent=new_text});export var remove_element=
_is_valid_element("remove_element")(function(element){element.remove()});export var rotate_element=_is_valid_element("rotate_element")(function(element,degrees){element.style.transform="rotate({}deg)".format(degrees)});export var vanish=_is_valid_element("vanish")(function(element){element.removeEventListener("click",element.click_handler);if(element.style.transition)element.style.transition+=", opacity 1s linear";else element.style.transition="opacity 1s linear";element.classList.add("fade-out");
setTimeout(remove_element.bind(null,element),2E3)});export var left=function(steps){if(typeof steps=="undefined"||steps!=null&&steps.hasOwnProperty("__kwargtrans__"))var steps=5;move(el,"left",steps,goal_check)};export var right=function(steps){if(typeof steps=="undefined"||steps!=null&&steps.hasOwnProperty("__kwargtrans__"))var steps=5;move(el,"right",steps,goal_check)};export var up=function(steps){if(typeof steps=="undefined"||steps!=null&&steps.hasOwnProperty("__kwargtrans__"))var steps=5;move(el,
"up",steps,goal_check)};export var down=function(steps){if(typeof steps=="undefined"||steps!=null&&steps.hasOwnProperty("__kwargtrans__"))var steps=5;move(el,"down",steps,goal_check)};export var background=function(image){change_bg(image,goal_check)};export var hide=function(element){if(typeof element=="undefined"||element!=null&&element.hasOwnProperty("__kwargtrans__"))var element=null;if(element)hide_el(goal_check,element);else hide_el(goal_check)};export var hit=function(power,direction){if(typeof direction==
"undefined"||direction!=null&&direction.hasOwnProperty("__kwargtrans__"))var direction="right";fire_weapon(power,goal_check,direction)};export var change_image=function(new_image){change_el_image(new_image,goal_check)};export var nearby_object=function(){return find_object()};export var py_update=function(key,text){update_powers(key,text,goal_check)};export var error=function(msg){show_error(msg,goal_check)};export var random=function(start,end){return int(random_py.randint(start,end))};export var letter=
function(){return random_py.choice("abcdefghijklmnopqrstuvwxyz")};export var popup=function(msg){popup_msg(msg,goal_check)};export var say=function(msg,time){player_says(msg,time,goal_check)};export var add_sound=function(file){return add_sound_el(file,goal_check)};export var play=function(id){play_sound(id,goal_check)};export var heading=function(text){change_heading(text,goal_check)};export var race=function(image,speed){race_obj(image,speed,goal_check)};export var clear_page=function(){clear_animations(goal_check)};
export var clear_screen=function(){clear_all(goal_check)};export var wait=function(time){wait_for(time,goal_check)};export var get_pizza=function(){change_image("assets/images/ufo-pizza.png",goal_check)};export var code=function(input_code){enter_code(input_code,goal_check)};export var countdown=function(num){if(typeof num=="undefined"||num!=null&&num.hasOwnProperty("__kwargtrans__"))var num=10;start_countdown(num,goal_check)};export var ignition=function(){ignite(el,"assets/images/rocketfire.png",
goal_check)};export var engine_off=function(){engineOff(el,"assets/images/rocket.png",goal_check)};

//# sourceMappingURL=wizardlib.map